# Site settings
title: Water Drop
email: your-email@domain.com
url: https://david-g-l.github.io/water-drop
description: "Droughts and Water Scarcity in the EU:<br> Economic Impact, Adaptation, Policy Implications and Integrated Assessment Modelling"
baseurl: "/grayscale-theme"

# Color settings
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
