# Site settings
title: WATER DROP
email: david.garcialeon@unive.it
url: http://David-G-L.github.io/water-drop
description: "Droughts and Water Scarcity in the EU:<br> Economic Impact, Adaptation, Policy Implications and Integrated Assessment Modelling"

owner:
  name: David 
  surname: Garc&iacutea-Le&oacuten
  google: 
    analytics: UA-56785827-4
    
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
 # - title: twitter
 #   url: https://twitter.com/SBootstrap
 
# Build settings
markdown: kramdown
permalink: pretty
